page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Space
        icon: block
        value:
          _section-type: space-block
      - label: Hero
        icon: star
        value:
          _section-type: hero
          hero_image:
          hero:
          hero-textarea:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Image and Textarea
        icon: image
        value:
          _section-type: image-and-textarea
          images:
            top_image:
            bottom_image:
          dark-heading:
          light-heading:
          1-textarea:
          quote:
          2-textarea:
          large-text:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Curved Image and Textarea
        icon: image
        value:
          _section-type: curved-image-and-textarea
          image:
          heading:
          textarea:
          social-media-links:
            instagram:
            tiktok:
            Facebook:
            twitter:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Call to Action
        icon: call
        value:
          _section-type: call-to-action
          image:
          button:
      - label: Projects
        icon: work
        value:
          _section-type: projects
          heading:
          first-project:
            image:
            subheading:
            textarea:
          second-project:
            image:
            subheading:
            textarea:
          third-project:
            image:
            subheading:
            textarea:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Recent Blogs
        icon: calendar
        value:
          _section-type: recent-blogs
          heading:
          textarea:
          cta:
          backgronud_image:
      - label: Form
        icon: article
        value:
          _section-type: form
          arch-background_image:
          heading:
          top:
            vertical-subheading:
            text-option-1:
            text-option-2:
            text-option-3:
          bottom:
            vertical-subheading:
            message:
          option-box:
            subheading:
            option-1:
            option-2:
            option-3:
            option-4:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - lable: Map
        icon: map
        value:
          _section-type: map
          heading:
          google-embed-code:
      - lable: Blog Cover Image
        icon: image
        value:
          _section-type: blog-cover
          blog_image:
      - lable: Blog Featured Textarea
        icon: text
        value:
          _section-type: blog-featured-textarea
          blog-featured-textarea:        
      - lable: Gallery
        icon: portfolio
        value:
          _section-type: gallery
          1_image:
          2_image:
          3_image:
          4_image:
          5_image:
          6_image:
