page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Space
        icon: block
        value:
          _section-type: space-block
      - label: Hero
        icon: star
        value:
          _section-type: hero
          hero_image:
          hero_html:
          hero-textarea_html:
          cta_html:
          cta-link:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Image and Textarea
        icon: image
        value:
          _section-type: image-and-textarea
          images:
            top_image:
            alt:
            bottom_image:
          dark-heading_html:
          light-heading_html:
          1-textarea_html:
          quote_html:
          2-textarea_html:
          large-text_html:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Curved Image and Textarea
        icon: image
        value:
          _section-type: curved-image-and-textarea
          image:
          heading_html:
          textarea_html:
          social-media-links:
            instagram:
            tiktok:
            Facebook:
            twitter:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Call to Action
        icon: call
        value:
          _section-type: call-to-action
          image:
          button_html:
      - label: Projects
        icon: work
        value:
          _section-type: projects
          heading_html:
          cta_html:
          first-project:
            image:
            first-alt:
            subheading_html:
            textarea_html:
          second-project:
            image:
            second-alt:
            subheading_html:
            textarea_html:
          third-project:
            image:
            third-alt:
            subheading_html:
            textarea_html:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Recent Blogs
        icon: schedule
        value:
          _section-type: recent-blogs
          heading_html:
          textarea_html:
          cta:
          blog-summary:
          background_image:
      - label: Form
        icon: article
        value:
          _section-type: form
          heading_html:
          signature_html:
          background_image:
          top:
            vertical-subheading_html:
            text-option-1_html:
            text-option-2_html:
            text-option-3_html:
          bottom:
            vertical-subheading_html:
            message_html:
          option-box:
            subheading_html:
            option-1_html:
            option-2_html:
            option-3_html:
            option-4_html:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Map
        icon: map
        value:
          _section-type: map
          description:  make sure to set width to 100%, height to 350 and style to border 2
          heading:
          google-embed-code:
      - label: Blog Cover Image
        icon: image
        value:
          _section-type: blog-cover-image
          blog-cover_image:
      - label: Blog Textarea
        icon: event
        value:
          _section-type: blog-textarea
          textarea_html:
      - label: Blog Featured Textarea
        icon: event
        value:
          _section-type: blog-featured-textarea
          blog-featured-textarea_html:
      - label: Gallery
        icon: apps
        value:
          _section-type: gallery
          1_image:
          2_image:
          3_image:
          4_image:
          5_image:
          6_image:
      - label: Blog Window Images
        icon: image
        value:
          _section-type: blog-window
          right_image:
          left_image:
      - label: Signature
        icon: title
        value:
          _section-type: signature
          signature_html:
