page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Space Block
        icon: block
        value:
          _section-type: space-block
      - label: Hero
        icon: star
        value:
          _section-type: hero
          hero_image:
          hero:
          hero-textarea:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Image and Textarea
        icon: image
        value:
          _section-type: image-and-textarea
          images:
            top_image:
            bottom_image:
          dark-heading:
          light-heading:
          1-textarea:
          quote:
          2-textarea:
          large-text:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Curved Image and Textarea
        icon: image
        value:
          _section-type: curved-image-and-textarea
          image:
          heading:
          textarea:
          social-media-links:
            instagram:
            tiktok:
            Facebook:
            twitter:  
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Call to Action
        icon: capital
        value:
          _section-type: call-to-action
          image:
          button:
      - label: Projects
        icon: work
        value:
          _section-type: projects
          heading:
          first-project:
            image:
            subheading:
            textarea:
          second-project:
            image:
            subheading:
            textarea:
          third-project:
            image:
            subheading:
            textarea:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Carousel
        icon: money
        value:
          _section-type: carousel
          heading:
          carousel:
            textarea:
            symbols:
            ending:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Form
        icon: article
        value:
          _section-type: form
          arch-background_image:
          heading:
          top:
            vertical-subheading:
            text-option-1:
            text-option-2:
            text-option-3:
          bottom:
            vertical-subheading:
            message:
          option-box:
            subheading:
            option-1:
            option-2:
            option-3:
            option-4:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
hero-font:
_select_data:
  fonts:
    - Cyrene
    - La Obrige
    - Lineal Simples
    - Maglony
    - Mak
    - Misto
    - Dream Avenue
    - Amatic SC, cursive
    - Barlow Condensed, sans-serif
    - Belleza, sans-serif
    - Kaushan Script, cursive
    - Montserrat, sans-serif
    - Oooh Baby, cursive
    - Playfair Display, serif
    - Poppins, sans-serif
    - Quicksand, sans-serif
    - Raleway, sans-serif
    - Roboto, sans-serif
headings-font:
_select_data:
  fonts:
      - Cyrene
      - La Obrige
      - Lineal Simples
      - Maglony
      - Mak
      - Misto
      - Dream Avenue
      - Amatic SC, cursive
      - Barlow Condensed, sans-serif
      - Belleza, sans-serif
      - Kaushan Script, cursive
      - Montserrat, sans-serif
      - Oooh Baby, cursive
      - Playfair Display, serif
      - Poppins, sans-serif
      - Quicksand, sans-serif
      - Raleway, sans-serif
      - Roboto, sans-serif
subheadings-font:
_select_data:
  fonts:
      - Cyrene
      - La Obrige
      - Lineal Simples
      - Maglony
      - Mak
      - Misto
      - Dream Avenue
      - Amatic SC, cursive
      - Barlow Condensed, sans-serif
      - Belleza, sans-serif
      - Kaushan Script, cursive
      - Montserrat, sans-serif
      - Oooh Baby, cursive
      - Playfair Display, serif
      - Poppins, sans-serif
      - Quicksand, sans-serif
      - Raleway, sans-serif
      - Roboto, sans-serif
text-font:
_select_data:
  fonts:
      - Cyrene
      - La Obrige
      - Lineal Simples
      - Maglony
      - Mak
      - Misto
      - Dream Avenue
      - Amatic SC, cursive
      - Barlow Condensed, sans-serif
      - Belleza, sans-serif
      - Kaushan Script, cursive
      - Montserrat, sans-serif
      - Oooh Baby, cursive
      - Playfair Display, serif
      - Poppins, sans-serif
      - Quicksand, sans-serif
      - Raleway, sans-serif
      - Roboto, sans-serif
